### ISSUE TITLE
Request - Include Autostand?

### ISSUE THREAD

**Issue by ghost** [jcon321/Zeal-TAKP#1]
First off, thank you for creating this limited version that doesn't require A/V modifications to run.

Would it be possible to include autostand?  Secrets has removed this from the Project Quarm files in favor of Zeal support, but I do not wish to run the full version of Zeal just for that functionality.  Thanks for your time!

**Comment by jcon321** [comment]
Hi, sorry it's not up to me what goes into TAKP approved Zeal, TAKP devs would make that call. I do not believe any more functionality will be added.
